### ISSUE TITLE
Tarn's Lair cluestep

### ISSUE THREAD

**Issue by TimOosterom** [TrevorMartz/tile-packs#1]
I'm not sure which method it uses, but it's not the fast one.

F loofy's way (through the normal entrance) is by far the fastest afaik: https://www.youtube.com/watch?v=syM2iZ_vzNM

Entrance within the haunted mine:
[{"regionId":13718,"regionX":32,"regionY":59,"z":0,"color":"#FFFFFFFF"}]

Tarn's lair:
[{"regionId":12615,"regionX":22,"regionY":8,"z":0,"color":"#50FFFFFF"},{"regionId":12615,"regionX":25,"regionY":15,"z":0,"color":"#50FFFFFF"},{"regionId":12615,"regionX":3,"regionY":10,"z":0,"color":"#50FFFFFF"},{"regionId":12615,"regionX":29,"regionY":15,"z":1,"color":"#50FFFFFF"}]

**Comment by TrevorMartz** [comment]
The tiles I added I had created myself.

Love this method too, will add this as a 2nd pack to have both options. Thanks.

**Comment by TrevorMartz** [comment]
finished
